---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ssh.controller.com
  resources:
  - sshcommandaudits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ssh.controller.com
  resources:
  - sshcommandaudits/finalizers
  verbs:
  - update
- apiGroups:
  - ssh.controller.com
  resources:
  - sshcommandaudits/status
  verbs:
  - get
  - patch
  - update
