//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SshCommandAudit) DeepCopyInto(out *SshCommandAudit) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SshCommandAudit.
func (in *SshCommandAudit) DeepCopy() *SshCommandAudit {
	if in == nil {
		return nil
	}
	out := new(SshCommandAudit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SshCommandAudit) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SshCommandAuditList) DeepCopyInto(out *SshCommandAuditList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SshCommandAudit, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SshCommandAuditList.
func (in *SshCommandAuditList) DeepCopy() *SshCommandAuditList {
	if in == nil {
		return nil
	}
	out := new(SshCommandAuditList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SshCommandAuditList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SshCommandAuditSpec) DeepCopyInto(out *SshCommandAuditSpec) {
	*out = *in
	if in.SshCommandEntity != nil {
		in, out := &in.SshCommandEntity, &out.SshCommandEntity
		*out = make([]*SshCommandEntity, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(SshCommandEntity)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SshCommandAuditSpec.
func (in *SshCommandAuditSpec) DeepCopy() *SshCommandAuditSpec {
	if in == nil {
		return nil
	}
	out := new(SshCommandAuditSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SshCommandAuditStatus) DeepCopyInto(out *SshCommandAuditStatus) {
	*out = *in
	if in.TotalCommands != nil {
		in, out := &in.TotalCommands, &out.TotalCommands
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SshCommandAuditStatus.
func (in *SshCommandAuditStatus) DeepCopy() *SshCommandAuditStatus {
	if in == nil {
		return nil
	}
	out := new(SshCommandAuditStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SshCommandEntity) DeepCopyInto(out *SshCommandEntity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SshCommandEntity.
func (in *SshCommandEntity) DeepCopy() *SshCommandEntity {
	if in == nil {
		return nil
	}
	out := new(SshCommandEntity)
	in.DeepCopyInto(out)
	return out
}
